kind: pipeline
type: kubernetes
name: pi-kube

platform:
  os: linux
  arch: arm

steps:
- name: deploy
  image: jtbarclay/drone-kubectl:latest
  settings:
    kubernetes_server:
      from_secret: k3s_server
    kubernetes_cert:
      from_secret: k3s_cert
    kubernetes_token:
      from_secret: k3s_token
  commands:
    - kubectl -n drone apply -f deployment.yml