kind: pipeline
type: exec
name: pi-exec

platform:
    os: linux
    arch: arm

steps:
    - name: killnode
      failure: ignore
      commands:
      - killall node

    - name: run
      commands:
      - npm install
      - npm start
