kind: pipeline
type: exec
name: pi-exec

platform:
    os: linux
    arch: arm

steps:
    - name: killnode
      failure: ignore
      commands:
      - killall node

    - name: install
      commands:
      - npm install

    - name: run
      detach: true
      commands:
      - npm start
