kind: pipeline
type: docker
name: pi-node

platform:
    os: linux
    arch: arm

steps:
    - name: server
      image: node
      commands:
      - npm install
      - npm start

trigger:
    branch:
        - master